### ISSUE TITLE
Str::slug not correct with specialchars, öäü

### ISSUE THREAD

**Issue by altsniffer** [mako-framework/framework#241] opened 2018-06-06 14:27 UTC
###  Description
---
Str::slug('test-überschrift');
expected: test%20%C3%BCberschrift
get: test-%C3-berschrift

did i forget some config or is this a bug with version 5?

### Versions & Platform
---

| What         | Version                  |
|--------------|--------------------------|
| PHP Version  | 7.x.x                    |
| Mako Version | 5.x.x                    |
| OS           | -                        |
| Database     | -                        |

**Comment by freost** [comment] 2018-06-06 20:29
I'm getting a different result when I'm testing (on both 7.2.3-1ubuntu1 and 7.0.22-0ubuntu0.16.04.1).

```test%C3%BCberschrift```

**Comment by altsniffer** [comment] 2018-06-06 20:53
Hmm thanks for testing it out :)

maybe its something with my local wrong (windows 10) i'll try it next days on a webserver.

**Comment by letr0n** [comment] 2018-06-07 11:02
Thats kinda weird. `/\s{1,}/` is just standard regex for one or more whitespace characters so it should work in all environments.

**Comment by altsniffer** [comment] 2018-06-07 11:09
Yap :)
I removed parts to check if there is some error, when i removed the preg_replace part, the output was correct, just without the -, so i tried str_replace instead of preg_replace and it works.

Maybe i should update my PHP Version from 7.0 to 7.2
must have something to do with rawurlencode, thats the only thing he changed :)

**Comment by freost** [comment] 2018-06-14 14:09
I'm unable to reproduce the bug on any of the environments I have tested on so I'm closing the issue.

**Closed by freost** 2018-06-14 14:09 UTC
Labels: bug, can't reproduce
